version: '3'
services:
    mailing:
        image: simple-mailing-service:latest
        environment:
            - FLASK_ENV=prod
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=developer
            - POSTGRES_DB_NAME=mailing
            - POSTGRES_TEST_DB_NAME=mail_test
            - POSTGRES_PROD_DB_NAME=mail_prod
            - POSTGRES_PASSWORD=password
            - CORS_ORIGINS=*
            - CORS_METHODS=GET,POST,PATCH,DELETE,OPTIONS
            - CORS_HEADERS=Origin,Authorization,Content-Type
            - HERRENCORP_BASE_URL=http://python.recruit.herrencorp.com
            - HERRENCORP_MAIL_AUTH=herren-recruit-python
            - HERRENCORP_SEND_MAIL_URL=/api/v1/mail
            - HERRENCORP_SEND_MAIL_URL_V2=/api/v2/mail
            - HERRENCORP_GET_MAIL_URL=/api/v1/inbox/
        ports:
            - "5000:5000"
        depends_on:
            - postgres
        restart: always
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_DB=mail_prod
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres-data:
        driver: local